name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]
  
jobs:
  check:
    name: Check & Validate
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # Fix for Rollup optional dependencies issue
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install
        
      - name: Lint code
        run: npm run lint
        
      - name: Build project
        run: npm run build